// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hwsmfbkktlnkzuyrlzax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3c21mYmtrdGxua3p1eXJsemF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMyMzI4ODUsImV4cCI6MjA4ODgwODg4NX0.Es5hbTAk5698do5bTQzNXZK17hcAF34TiHfyhuOYiDQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});